# fly.toml app configuration file generated for commandly-frontend on 2025-04-09T16:30:55+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'commandly-frontend'
primary_region = 'sin'

[build]
  [build.args]
    NODE_ENV = "production"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[http_service.headers]]
    for = "/**"
    [http_service.headers.values]
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Permissions-Policy = "camera=(), microphone=(), geolocation=()"
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://commandly-backend.fly.dev;"

  # Catch-all route for all paths
  [[http_service.routes]]
    from = "/**"
    to = "/index.html"
    methods = ["GET"]

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
